INSERT INTO Cuisine (id, name) VALUES (1, 'American');
INSERT INTO Cuisine (id, name) VALUES (2, 'Chinese');
INSERT INTO Cuisine (id, name) VALUES (3, 'Thai');
INSERT INTO Cuisine (id, name) VALUES (4, 'Italian');
INSERT INTO Cuisine (id, name) VALUES (5, 'French');
INSERT INTO Cuisine (id, name) VALUES (6, 'Japanese');
INSERT INTO Cuisine (id, name) VALUES (7, 'Turkish');
INSERT INTO Cuisine (id, name) VALUES (8, 'Korean');
INSERT INTO Cuisine (id, name) VALUES (9, 'Vietnamese');
INSERT INTO Cuisine (id, name) VALUES (10, 'Indian');
INSERT INTO Cuisine (id, name) VALUES (11, 'Spanish');
INSERT INTO Cuisine (id, name) VALUES (12, 'Greek');
INSERT INTO Cuisine (id, name) VALUES (13, 'Mexican');
INSERT INTO Cuisine (id, name) VALUES (14, 'Malaysian');
INSERT INTO Cuisine (id, name) VALUES (15, 'African');
INSERT INTO Cuisine (id, name) VALUES (16, 'German');
INSERT INTO Cuisine (id, name) VALUES (17, 'Indonesian');
INSERT INTO Cuisine (id, name) VALUES (18, 'Russian');
INSERT INTO Cuisine (id, name) VALUES (19, 'Other');


INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Deliciousgenix', 4, 1, 10, 11);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Herbed Delicious', 4, 7, 20, 9);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Deliciousscape', 3, 7, 50, 1);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Hideaway Delicious', 2, 5, 40, 12);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Cuts Delicious', 3, 9, 25, 8);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Lord Delicious', 1, 7, 35, 18);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Hilltop Delicious', 3, 3, 45, 6);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Fine Delicious', 4, 5, 45, 4);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Deliciousish', 1, 3, 50, 12);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Havana Delicious', 3, 1, 35, 8);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Deliciouspad', 3, 10, 40, 13);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Deliciousbea', 5, 6, 50, 15);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Deliciousquipo', 2, 2, 10, 19);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Fed Delicious', 2, 9, 35, 4);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Hotspot Delicious', 4, 10, 25, 13);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Gusto Delicious', 5, 3, 50, 2);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Deliciouszen', 2, 6, 30, 5);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Deliciouszilla', 4, 1, 15, 2);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Deliciousio', 5, 9, 40, 19);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Local Delicious', 5, 4, 20, 12);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Crisp Delicious', 5, 2, 45, 18);
INSERT INTO Restaurant (name, customer_rating, distance, price, cuisine_id) VALUES ('Deliciousoryx', 1, 5, 25, 2);
